// <auto-generated />
using System;
using LimeHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LimeHub.Migrations
{
    [DbContext(typeof(LimeHubDbContext))]
    [Migration("20250629110747_addShoppingCartItem")]
    partial class addShoppingCartItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LimeHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Xe moto classic với động cơ V-Twin mạnh mẽ.",
                            ImageUrl = "https://d2bywgumb0o70j.cloudfront.net/2021/01/20/220b7566e1ba42e4bafe043cb3d6846b_4a03e718d1581c31.jpg",
                            IsTrendingProduct = false,
                            Name = "Harley-Davidson Iron 883",
                            Price = 25000
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Xe sportbike tầm trung, linh hoạt và tốc độ.",
                            ImageUrl = "https://thuongmotor.com/wp-content/uploads/2020/11/Kawasaki-Ninja-400-ABS-SE-01.jpg",
                            IsTrendingProduct = false,
                            Name = "Kawasaki Ninja 400",
                            Price = 18000
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Xe naked bike với mô-men xoắn cao, dễ lái.",
                            ImageUrl = "https://motorrock.com.vn/upload/hinhanh/mt077431.jpg",
                            IsTrendingProduct = false,
                            Name = "Yamaha MT-07",
                            Price = 20000
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Xe naked bike hiệu suất cao từ Ý.",
                            ImageUrl = "https://vuongkhangmotor.com/upload/product/444-7625-6153.jpg",
                            IsTrendingProduct = false,
                            Name = "Ducati Monster",
                            Price = 30000
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Xe adventure touring hàng đầu, phù hợp mọi địa hình.",
                            ImageUrl = "https://autopro8.mediacdn.vn/2021/12/20/7r1250gs-1639988992690260853955.jpg",
                            IsTrendingProduct = false,
                            Name = "BMW R 1250 GS",
                            Price = 35000
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Xe sportbike đa dụng, cân bằng giữa hiệu suất và sự thoải mái.",
                            ImageUrl = "https://hondamotor.vn/upload/hinhanh/cbr650r3712.jpg",
                            IsTrendingProduct = false,
                            Name = "Honda CBR650R",
                            Price = 22000
                        });
                });

            modelBuilder.Entity("LimeHub.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("LimeHub.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("LimeHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
