// <auto-generated />
using System;
using LimeHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LimeHub.Migrations
{
    [DbContext(typeof(LimeHubDbContext))]
    partial class LimeHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LimeHub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineDisplacement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelTransmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.Property<int>("YearsUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Xe moto classic với động cơ V-Twin mạnh mẽ.",
                            ImageUrl = "https://d2bywgumb0o70j.cloudfront.net/2021/01/20/220b7566e1ba42e4bafe043cb3d6846b_4a03e718d1581c31.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 2024,
                            Mileage = 15000,
                            EngineDisplacement = "750cc",
                            Name = "Harley-Davidson Iron 883",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 25000000,
                            ViewsCount = 3,
                            YearsUsed = 1,
                            Color = "Đen",
                            Location= "Mĩ"
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Xe sportbike tầm trung, linh hoạt và tốc độ.",
                            ImageUrl = "https://thuongmotor.com/wp-content/uploads/2020/11/Kawasaki-Ninja-400-ABS-SE-01.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 2022,
                            Mileage = 14000,
                            EngineDisplacement = "750cc",
                            Name = "Kawasaki Ninja 400",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18000,
                            ViewsCount = 0,
                            YearsUsed = 0,
                            Color = "Xanh lá",
                            Location= "China"
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Xe naked bike với mô-men xoắn cao, dễ lái.",
                            ImageUrl = "https://motorrock.com.vn/upload/hinhanh/mt077431.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 2025,
                            Mileage = 12000,
                            EngineDisplacement = "750cc",
                            Name = "Yamaha MT-07",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 20000,
                            ViewsCount = 300,
                            YearsUsed = 0,
                            Color="Xám",
                            Location= "Pháp"
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Xe naked bike hiệu suất cao từ Ý.",
                            ImageUrl = "https://vuongkhangmotor.com/upload/product/444-7625-6153.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 0,
                            Mileage = 0,
                            EngineDisplacement = "750cc",
                            Name = "Ducati Monster",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30000,
                            ViewsCount = 0,
                            YearsUsed = 2,
                            Color= "Đỏ",
                            Location= "Italya"
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Xe adventure touring hàng đầu, phù hợp mọi địa hình.",
                            ImageUrl = "https://autopro8.mediacdn.vn/2021/12/20/7r1250gs-1639988992690260853955.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 0,
                            Mileage = 0,
                            EngineDisplacement = "750cc",
                            Name = "BMW R 1250 GS",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 35000,
                            ViewsCount = 0,
                            YearsUsed = 0,
                            Color= "Vàng",
                            Location="Nga"
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Xe sportbike đa dụng, cân bằng giữa hiệu suất và sự thoải mái.",
                            ImageUrl = "https://hondamotor.vn/upload/hinhanh/cbr650r3712.jpg",
                            IsTrendingProduct = false,
                            ManufactureYear = 0,
                            Mileage = 0,
                            EngineDisplacement = "750cc",
                            Name = "Honda CBR650R",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 22000,
                            ViewsCount = 0,
                            YearsUsed = 00,
                            Color= "Đỏ",
                            Location= "Nhật"
                        });
                });

            modelBuilder.Entity("LimeHub.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("LimeHub.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("LimeHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
